apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: test-job-1
spec:
  queue: default
  tasks:
    - replicas: 1
      name: "default-sleep"
      template:
        metadata:
          name: web
        spec:
          containers:
            - name: sleep
              imagePullPolicy: IfNotPresent
              image: governmentpaas/curl-ssl
              command: ["/bin/sleep", "30s"]
              resources:
                requests:
                  cpu: "10Mi"
                  memory: "100m"
          restartPolicy: OnFailure
